name: Development
on:
  push:
    branches: [main]
  # pull_request:
  # branches: [ main ]

jobs:
  build-and-deploy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo ok.
