name: CD
concurrency: production
on:
  push:
    branches: [main]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    -name: Deployment
    uses: root
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      pass: ${{ secrets.SSH_PASSWORD }}
      srcipt: |
        cd /root/dingding2
        sudo -u root git pull --ff-only
        sudo -u root npm i
        sudo -u root npm run build
