name: Production
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/sunday
            wget https://github.com/graywenn/sunday/archive/${{github.ref}}.tar.gz -O ${{github.ref_name}}.tar.gz
            tar xzvf ${{github.ref_name}}.tar.gz --strip-components 1
            cp ../configs/.env ./
            npm i
            npm run build
