name: Production
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          npm install
          npm run build

      - name: Upload
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          scp_source: "./dist/"
          scp_target: "/root/sunday/"
          before_script: |
            mkdir sunday-backup -p
            current_time=$(date "+%Y%m%d%H%M") && cp -r sunday sunday-backup/$current_time
            rm -r sunday
          after_script: |
            nginx -s reload
